- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/KafkaInterceptor.java
Added taxCode to UserToSend notification mapping
Missing user TaxCode in notification sent to FD topic
deployed from branch and tested doing a user onboarding
> add user TaxCode to userNotification

- app/src/main/resources/config/application.yml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- helm/values.yaml
- web/src/main/java/it/pagopa/selfcare/external_interceptor/web/controller/InterceptorController.java
Changed ingress url, and logs
Ingress url was wrong
deployed from branch and tested using apim
> Fix controller base path

- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/KafkaInterceptor.java
- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/KafkaSend.java
- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendFdNotification.java
- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendSapNotification.java
Add log filter for sensible user datas
Logs shouldn't contain fiscal code of users
> add confidential log filter

- connector/rest/src/main/resources/config/prod-fd-rest-client.properties
- connector/rest/src/main/resources/config/token-fd-rest-client.properties
Updated fd restClient login path
Product has updated their endpoint
> update fd login path

- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/institution/NotificationType.java
fix relationship mapping for deleted state
> fix deleted user relationship state

- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/config/KafkaProducerConfig.java
- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/KafkaSend.java
- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendFdNotification.java
set updated at from external interceptor
> set updated at from external interceptor

- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/institution/OnboardingStatus.java
- core/src/main/java/it/pagopa/selfcare/external_interceptor/core/SchedulerServiceImpl.java
- core/src/main/resources/config/core-config.properties
- core/src/test/java/it/pagopa/selfcare/external_interceptor/core/SchedulerServiceImplTest.java
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
Aggiornamento valore e chiave necessari per il resend dei token dei prodotti verso sap
la stringa del valore era scritta in maniera sbagliata
> Aggiornamento values yaml di helm

- core/src/main/java/it/pagopa/selfcare/external_interceptor/core/SchedulerServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_interceptor/core/SchedulerServiceImplTest.java
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
Update common version in pom
new commons released with a new InstitutionType
> update commons version in pom

- connector/rest/src/main/resources/config/application.properties
- core/src/main/java/it/pagopa/selfcare/external_interceptor/core/SchedulerServiceImpl.java
Adding error decorder to rest clients
> add error decorder

- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/institution/Notification.java
- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/institution/NotificationToSend.java
- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/institution/OnboardedProduct.java
- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/ms_core/Token.java
- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/user/OnboardedUserProduct.java
- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/user/UserNotification.java
- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/KafkaInterceptor.java
- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/KafkaSend.java
- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendFdNotification.java
- connector/kafka-manager/src/test/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/KafkaInterceptorTest.java
- connector/rest/docs/openapi/api-selfcare-core-docs.json
- connector/rest/pom.xml
- connector/rest/src/main/java/it/pagopa/selfcare/external_interceptor/connector/rest/MsCoreConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_interceptor/connector/rest/client/MsCoreRestClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_interceptor/connector/rest/client/PartyRegistryProxyRestClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_interceptor/connector/rest/model/mapper/MsCoreMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_interceptor/connector/rest/MsCoreConnectorImplTest.java
…st clients (#40)
* implement open-api tool to create rest clients
* remove commented lines
* refactor lambda
> release-uat

- connector/rest/src/main/java/it/pagopa/selfcare/external_interceptor/connector/rest/interceptor/RegistryProxyAuthorizationHeaderInterceptor.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_interceptor/connector/rest/model/mapper/EntityMapper.java
- connector/rest/src/main/resources/config/registry-proxy-rest-client.properties
> Conflict uat

- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendSapNotification.java
- connector/kafka-manager/src/main/resources/config/kafka-manager.properties
- connector/kafka-manager/src/test/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendSapNotificationTest.java
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
Control on origin has been made configurable
since now the fields city, county country are available also for the non IPA institutions, the check has been made configurable, so it can be set to choose which origins are allowed
> [SELC-3265] feat: removed check on Origin field for non ipa institution

- CODEOWNERS
Selfcare-contributors as codeowner
> ops: selfcare-contributors as codeowner

- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/institution/Institution.java
feat: add category field to notification object read from queue
notification model update
> [SELC-3415] feat: add category field to notification object read from queue

- helm/values-dev.yaml
Set resource requests and limits in deployment manifest
Everypod should run under some limit
> [SELC-3485] Set resource request and limits - DEV 

- .devops/deploy-pipelines.yml
- helm/values-dev.yaml
- helm/values-uat.yaml
> [SELC-3491] Set resource request and limits - UAT

- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/mapper/NotificationMapper.java
User message record id set to be random
Due to implementations done upstream, the new record id the interceptor will be receiving is a combination of userId+institutionId+productId+productRole, Fideiussioni digitali needs the id to be in UUID format, so the id string from core is overwritten with a random uuid
> Set user record id to random uuid

- pom.xml
> Release UAT

- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendSapNotification.java
- connector/kafka-manager/src/test/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendSapNotificationTest.java
- modify description field for AOO/UO in SAP queue message
This change arises from the need of modify description field for AOO/UO in SAP queue message.
In case of AOO/UO subunit types the description must be _"rootParent description - institution description"_.
This change has been tested locally by doing an onboarding and checking SAP queue.
> [SELC-3812] feat: modify description field for AOO/UO in SAP queue message

- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendFdNotification.java
- Add limit productid for update only prod-fd or prod-fd-garantito
Check if event.productId is prod-fd*
> SELC-4060: fix: Notification event compliant to avro schema

- .github/workflows/release_ms_pnpg.yml
Add workflow to deploy to pnpg container app
Migrating to container app
> [EC-153] Add microservice PNPG pipeline

- .github/workflows/release_ms.yml
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
JWT_TOKEN_PUBLIC_KEY misses as env variable
> [EC-122] fix: added JWT_TOKEN_PUBLIC_KEY as secret

- helm/values-dev.yaml
Set replica to 0 on deployment k8s
Migration to Container Apps
> chore: deployment k8s replica 0 dev

- .github/workflows/pr_ms.yml
- .github/workflows/release_ms.yml
- infra/container_apps/README.md
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/locals.tf
- infra/container_apps/main.tf
- infra/container_apps/variables.tf
* Container App env name must be specified
* workload_profile null for dev and prod
Container App env could have a different configuration among dev or uat or prod.
> chore: Migration to Container App module with name and workload_profile empty

- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/mapper/NotificationMapper.java
- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/user/UserNotification.java
- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/user/UserProductDetails.java
- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendFdNotification.java
- connector/kafka-manager/src/test/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendFdNotificationTest.java
- connector/rest/src/main/resources/config/application.properties
Switching api to external-api-be v2 api
Due to the migration of user entities to the new user-ms app, new API versions has been released that retrieve the infos from the new microservice.
Locally run and tested
> [SELC-4687] feat: switch to v2 external-api-backend

- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/locals.tf
- infra/container_apps/main.tf
- infra/container_apps/variables.tf
Using terraform ca module with suffix
> chore: Migration uat using terraform ca module with suffix

- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/institution/Billing.java
- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/institution/BillingToSend.java
- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/institution/Institution.java
- connector-api/src/main/java/it/pagopa/selfcare/external_interceptor/connector/model/institution/NotificationToSend.java
- connector/kafka-manager/src/main/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendSapNotification.java
- connector/kafka-manager/src/test/java/it/pagopa/selfcare/external_interceptor/connector/kafka_manager/factory/SendSapNotificationTest.java
added distinct billing in model of message to send
SAP and FD topics don't accept taxCodeInvoicing field in billing node. So we had to distinct the model of Billing node for message to send
junit
> [SELC-4785] fix: added distinct billing in model of message to send
